/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ManifestoPoint = IDL.Text;
export const PartyInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
});

export const idlService = IDL.Service({
  'getManifestoPoints' : IDL.Func([], [IDL.Vec(ManifestoPoint)], ['query']),
  'getPartyInfo' : IDL.Func([], [PartyInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ManifestoPoint = IDL.Text;
  const PartyInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
  });
  
  return IDL.Service({
    'getManifestoPoints' : IDL.Func([], [IDL.Vec(ManifestoPoint)], ['query']),
    'getPartyInfo' : IDL.Func([], [PartyInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };